
public enum Proteus2 {
  
  static let editorTruss = Proteus.createEditorTruss("Proteus/2", voice: Voice.patchTruss, voiceBank: Voice.bankTruss, presets: presets)
  public static let moduleTruss = Proteus.createModuleTruss(editorTruss, subid: "proteus2", chorusMax: Voice.chorusMax)


  static let presets = ["Solo Cello", "Solo Viola", "Solo Violin", "Quartet", "Solo Chamber", "Arco Basses", "Arco Celli", "Arco Violas", "Arco Violins", "Marcato 1", "Marcato 2", "Legato Str", "Concerto", "Pizz Basses", "Pizz Celli", "Pizz Violas", "Pizz Violins", "Pizzicato 1", "Pizzicato 2", "Trem Strings", "Tremulus", "Strgs/Flutes", "Resting Pad", "Divertimento", "Flute", "Piccolo", "Oboe", "English Horn", "Clarinet", "Bass Clarinet", "Bassoon", "Contrbassoon", "Chamber Winds", "Section Winds", "Epilogue", "Wind Stack", "French Horn 1", "French Horn 2", "Section Horns", "Trumpet 1", "Trumpet 2", "Two Trumpets", "Harmon Mute", "Trombone 1", "Trombone 2", "Tuba", "Back Brass", "Bright Brass", "Chamber Brass", "BrassStrings", "Timpani", "Gong/Cymbal", "Bass/Snare +", "Temple Block", "Xylophone", "Glockenspiel", "Celesta", "Tubular Bells", "Percussion 1", "Percussion 2", "Harp", "Harpstrings", "Harpsikord", "Notre Dame", "Winter Signs", "Deep Pad", "Portamento/F", "Bell Ensemble", "Cyberspace", "PizzMoogBass", "Marimbala", "Grim Reaper", "Tinker Bell", "Carousel", "Exotic Harp", "Darn Saucers", "Bronze Pad", "Vibraphone", "Astral Flute", "Kool Bass", "Sombre Winds", "Space Cowboy", "The Machine", "Early Perc", "Gently Now", "Piccolodeeyo", "Infinite One", "ShimmerWays", "Turbo Bass", "Requiem", "Wrong Room", "Analog Pad", "Chapel Organ", "Electrovocal", "Fat Boy Tuba", "SawBass/Lead", "Vienna Dream", "Vertigo Pad", "Tarkus Twin", "RoomOfStrings", "Magic Bells", "Reginatron", "Sub It!", "Psychlotron", "CloudChamber", "Sepulcher", "Lurch Pluck", "Pizz/Piccolo", "Vampirical", "String Thing", "Galapagos", "Square One", "Square Link", "<*>", "Sardonicus", "Master Tron", "Lo Wind Inst", "Sympathetic", "Wind Chimes", "Boat Haus", "Glitter God", "Story Bass", "Nice Night", "Prophet Lead", "Prophet Link", "Whistl'n Joe", "Link2Shimmer", "Ascending", "Harpsomatic", "Phaedra", "Cimbalon", "Recorder", "Koto", "Dream Garden", "Amplify Bass", "Asian Reed", "Soft Harp", "Jazz Bass", "Grandfather", "Classic Gtr", "Temple Bell", "StrHarmonic", "Cellophane", "Gamba Musik", "Quintoctave", "Basses&Vios", "Violin&Celli", "ArcoViolins", "Arco Duet", "Str Section", "Arco Strings", "In The Pit", "<<InThePit<<", "Rotary Chmbr", "Krummhorns", "C.Bsn/Dbl Bs", "Soft Flute", "Hi Wind Solo", "Verb Clarinet", "PiccoloPeace", "Flute/Oboe", "Clar./Flute", "Clar/Bassoon", "Double Reeds", "Bassoon/Horn", "Alto Flute", "WindEnsemble", "DblReeds/Hrn", "Verb Horn", "Xprsv Cornet", "Bone&Trumpet", "Bone&Tuba", "Trombones", "Sfz Brass", "Horn Vel+Wh", "Afroblocks", "Timba Mallet", "Timp w/Tone", "Bass Drum", "TimpLowBlock", "Deep Drum", "Triangle", "Big Log", "Gamelan", "Clarinet/Bb", "Clarinet/A", "BassClar/Bb", "EngHorn/F", "FrenchHorn/F", "Trumpet/Bb", "Trumpet/D", "Default"]
}
