
class TG77Algorithms {
  
  static let all : [DXAlgorithm] = {
    var algos = [DXAlgorithm]()
    
    let arrays : [[[String:[Int]]]] = [
      [ // 1
        [:],
        ["outs" : [1]],
        ["outs" : [2]],
        ["outs" : [3]],
        ["outs" : [4]],
        ["outs" : [5]],
        ],
      [ // 2
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [4]], // 6
      ],
      [ // 3
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [3]], // 6
      ],
      [ // 4
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [2]], // 6
      ],
      [ // 5
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [1]], // 6
      ],
      [ // 6
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [3]], // 5
        ["outs" : [3]], // 6
      ],
      [ // 7
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [2]], // 5
        ["outs" : [5]], // 6
      ],
      [ // 8
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [2]], // 5
        ["outs" : [2]], // 6
      ],
      [ // 9
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [2]], // 4
        ["outs" : [4]], // 5
        ["outs" : [4]], // 6
      ],
      [ // 10
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [1]], // 5
        ["outs" : [5]], // 6
      ],
      [ // 11
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [1]], // 5
        ["outs" : [1]], // 6
      ],
      [ // 12
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [1]], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [4]], // 6
      ],
      [ // 13
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [1]], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [3]], // 6
      ],
      [ // 14
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [2]], // 4
        ["outs" : [2]], // 5
        ["outs" : [2]], // 6
      ],
      [ // 15
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [1]], // 3
        ["outs" : [3]], // 4
        ["outs" : [3]], // 5
        ["outs" : [3]], // 6
      ],
      [ // 16
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [1]], // 4
        ["outs" : [4]], // 5
        ["outs" : [1]], // 6
      ],
      [ // 17
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [1]], // 4
        ["outs" : [4]], // 5
        ["outs" : [4]], // 6
      ],
      [ // 18
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [1]], // 4
        ["outs" : [1]], // 5
        ["outs" : [1]], // 6
      ],
      [ // 19
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        ["outs" : [1]], // 4
        ["outs" : [1]], // 5
        ["outs" : [2], "feedOuts" : [6]], // 6
      ],
      [ // 20
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [1]], // 3
        ["outs" : [1]], // 4
        ["outs" : [1]], // 5
        ["outs" : [1]], // 6
      ],
      [ // 21
        [:], // 1
        [:], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [5]], // 6
      ],
      [ // 22
        [:], // 1
        [:], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [4]], // 6
      ],
      [ // 23
        [:], // 1
        [:], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [3]], // 6
      ],
      [ // 24
        [:], // 1
        [:], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [2]], // 6
      ],
      [ // 25
        [:], // 1
        [:], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [3]], // 5
        ["outs" : [3]], // 6
      ],
      [ // 26
        [:], // 1
        [:], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [2]], // 5
        ["outs" : [5]], // 6
      ],
      [ // 27
        [:], // 1
        [:], // 2
        ["outs" : [2]], // 3
        ["outs" : [3]], // 4
        ["outs" : [2]], // 5
        ["outs" : [2]], // 6
      ],
      [ // 28
        [:], // 1
        [:], // 2
        ["outs" : [2]], // 3
        ["outs" : [2]], // 4
        ["outs" : [4]], // 5
        ["outs" : [4]], // 6
      ],
      [ // 29
        [:], // 1
        [:], // 2
        ["outs" : [2]], // 3
        ["outs" : [2]], // 4
        ["outs" : [2]], // 5
        ["outs" : [2]], // 6
      ],
      [ // 30
        [:], // 1
        ["outs" : [1]], // 2
        [:], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [5]], // 6
      ],
      [ // 31
        [:], // 1
        ["outs" : [1]], // 2
        [:], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [4]], // 6
      ],
      [ // 32
        [:], // 1
        ["outs" : [1]], // 2
        [:], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [3]], // 6
      ],
      [ // 33
        [:], // 1
        ["outs" : [1]], // 2
        [:], // 3
        ["outs" : [3]], // 4
        ["outs" : [3]], // 5
        ["outs" : [3]], // 6
      ],
      [ // 34
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        [:], // 4
        ["outs" : [4]], // 5
        ["outs" : [5]], // 6
      ],
      [ // 35
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [2]], // 3
        [:], // 4
        ["outs" : [4]], // 5
        ["outs" : [4]], // 6
      ],
      [ // 36
        [:], // 1
        ["outs" : [1]], // 2
        ["outs" : [1], "feedOuts" : [3]], // 3
        [:], // 4
        ["outs" : [4]], // 5
        ["outs" : [4]], // 6
      ],
      [ // 37
        [:], // 1
        [:], // 2
        [:], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [5]], // 6
      ],
      [ // 38
        [:], // 1
        [:], // 2
        [:], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [4]], // 6
      ],
      [ // 39
        [:], // 1
        [:], // 2
        [:], // 3
        ["outs" : [3]], // 4
        ["outs" : [4]], // 5
        ["outs" : [3]], // 6
      ],
      [ // 40
        [:], // 1
        [:], // 2
        ["outs" : [1,2], "feedOuts" : [3]], // 3
        [:], // 4
        ["outs" : [4]], // 5
        ["outs" : [5]], // 6
      ],
      [ // 41
        [:], // 1
        [:], // 2
        ["outs" : [1,2], "feedOuts" : [3]], // 3
        [:], // 4
        ["outs" : [4]], // 5
        ["outs" : [4]], // 6
      ],
      [ // 42
        [:], // 1
        ["outs" : [1]], // 2
        [:], // 3
        ["outs" : [3]], // 4
        [:], // 5
        ["outs" : [5]], // 6
      ],
      [ // 43
        [:], // 1
        [:], // 2
        [:], // 3
        [:], // 4
        ["outs" : [1,2,3,4], "feedOuts" : [5,6]], // 5
        ["outs" : [1,2,3,4,5], "feedOuts" : [6]], // 6
      ],
      [ // 44
        [:], // 1
        [:], // 2
        [:], // 3
        [:], // 4
        [:], // 5
        ["outs" : [1,2,3,4,5], "feedOuts" : [6]], // 6
      ],
      [ // 45
        [:], // 1
        [:], // 2
        [:], // 3
        [:], // 4
        [:], // 5
        [:], // 6
      ],
      ]
    
    return arrays.map { DXAlgorithm($0) }
  }()
  
  // Algos numbers in comments are 0-based counting (i.e. actual Algo value
  static let paramValues : [[SynthPath:Int]] = [

    // 0,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],
    
    // 1,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 9,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 0,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 2,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 9,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 3,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 9,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 4,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 9,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 5,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 9,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 6,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 9,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 0,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 0,
      [.i(5), .feedback, .src, .i(1)] : 1,
      [.i(5), .adjust, .level] : 0,
    ],

    // 7,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 9,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 8,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 9,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 3,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 9,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 0,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 9,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 9,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 0,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 0,
      [.i(5), .feedback, .src, .i(1)] : 1,
      [.i(5), .adjust, .level] : 0,
    ],

    // 10,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 9,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 11,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 9,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 3,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 9,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 12,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 9,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 3,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 9,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 13,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 9,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 3,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 14,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 9,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 3,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 9,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 2,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 0,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 15,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 9,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 3,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 16,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 9,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 3,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 9,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 0,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 17,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 9,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 18,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 9,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 3,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 3,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 0,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 6,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 0,
      [.i(5), .feedback, .src, .i(1)] : 1,
      [.i(5), .adjust, .level] : 0,
    ],

    // 19,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 9,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 0,
      [.i(0), .adjust, .level] : 0,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 3,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 20,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 0,
      [.i(1), .adjust, .level] : 1,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 21,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 0,
      [.i(1), .adjust, .level] : 1,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 3,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 9,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 22,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 0,
      [.i(1), .adjust, .level] : 1,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 9,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 23,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 9,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 0,
      [.i(1), .adjust, .level] : 1,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 24,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 0,
      [.i(1), .adjust, .level] : 1,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 9,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 25,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 9,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 0,
      [.i(1), .adjust, .level] : 1,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 0,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 0,
      [.i(5), .feedback, .src, .i(1)] : 1,
      [.i(5), .adjust, .level] : 0,
    ],

    // 26,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 9,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 0,
      [.i(1), .adjust, .level] : 1,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 27,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 9,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 0,
      [.i(1), .adjust, .level] : 1,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 3,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 9,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 0,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 28,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 9,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 0,
      [.i(1), .adjust, .level] : 1,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 3,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 29,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 3,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 1,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 30,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 3,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 1,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 9,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 31,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 3,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 9,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 1,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 32,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 3,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 9,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 1,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 2,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 0,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 33,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 3,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 0,
      [.i(3), .adjust, .level] : 1,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 34,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 3,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 9,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 0,
      [.i(3), .adjust, .level] : 1,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 35,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 3,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 1,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 6,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 1,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 9,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 0,
      [.i(3), .adjust, .level] : 1,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 3,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 2,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 36,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 3,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 3,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 3,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 37,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 3,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 3,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 3,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 9,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 38,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 3,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 3,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 9,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 0,
      [.i(2), .adjust, .level] : 3,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 39,
    [
      [.i(0), .src, .i(0)] : 3,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 3,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 3,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 6,
      [.i(2), .dest] : 1,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 0,
      [.i(3), .adjust, .level] : 3,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 3,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 2,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 40,
    [
      [.i(0), .src, .i(0)] : 3,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 3,
      [.i(1), .src, .i(0)] : 1,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 3,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 6,
      [.i(2), .dest] : 1,
      [.i(2), .feedback, .src, .i(0)] : 0,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 0,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 9,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 0,
      [.i(3), .adjust, .level] : 3,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 3,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 2,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 41,
    [
      [.i(0), .src, .i(0)] : 1,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 3,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 3,
      [.i(1), .feedback, .src, .i(0)] : 0,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 0,
      [.i(2), .src, .i(0)] : 1,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 3,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 2,
      [.i(3), .feedback, .src, .i(0)] : 0,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 0,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 0,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 0,
      [.i(4), .adjust, .level] : 3,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 0,
      [.i(5), .feedback, .src, .i(1)] : 1,
      [.i(5), .adjust, .level] : 0,
    ],

    // 42,
    [
      [.i(0), .src, .i(0)] : 4,
      [.i(0), .src, .i(1)] : 3,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 4,
      [.i(1), .src, .i(0)] : 4,
      [.i(1), .src, .i(1)] : 3,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 4,
      [.i(2), .src, .i(0)] : 4,
      [.i(2), .src, .i(1)] : 3,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 4,
      [.i(3), .src, .i(0)] : 1,
      [.i(3), .src, .i(1)] : 3,
      [.i(3), .dest] : 0,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 0,
      [.i(3), .adjust, .level] : 4,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 7,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 0,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 0,
      [.i(5), .src, .i(0)] : 6,
      [.i(5), .src, .i(1)] : 7,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 0,
    ],

    // 43,
    [
      [.i(0), .src, .i(0)] : 3,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 5,
      [.i(1), .src, .i(0)] : 3,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 5,
      [.i(2), .src, .i(0)] : 3,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 5,
      [.i(3), .src, .i(0)] : 3,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 5,
      [.i(4), .src, .i(0)] : 1,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 0,
      [.i(4), .adjust, .level] : 5,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 6,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 0,
      [.i(5), .feedback, .src, .i(1)] : 1,
      [.i(5), .adjust, .level] : 0,
    ],

    // 44,
    [
      [.i(0), .src, .i(0)] : 0,
      [.i(0), .src, .i(1)] : 0,
      [.i(0), .dest] : 0,
      [.i(0), .feedback, .src, .i(0)] : 1,
      [.i(0), .feedback, .src, .i(1)] : 1,
      [.i(0), .adjust, .level] : 6,
      [.i(1), .src, .i(0)] : 0,
      [.i(1), .src, .i(1)] : 0,
      [.i(1), .dest] : 0,
      [.i(1), .feedback, .src, .i(0)] : 1,
      [.i(1), .feedback, .src, .i(1)] : 1,
      [.i(1), .adjust, .level] : 6,
      [.i(2), .src, .i(0)] : 0,
      [.i(2), .src, .i(1)] : 0,
      [.i(2), .dest] : 0,
      [.i(2), .feedback, .src, .i(0)] : 1,
      [.i(2), .feedback, .src, .i(1)] : 1,
      [.i(2), .adjust, .level] : 6,
      [.i(3), .src, .i(0)] : 0,
      [.i(3), .src, .i(1)] : 0,
      [.i(3), .dest] : 3,
      [.i(3), .feedback, .src, .i(0)] : 1,
      [.i(3), .feedback, .src, .i(1)] : 1,
      [.i(3), .adjust, .level] : 6,
      [.i(4), .src, .i(0)] : 0,
      [.i(4), .src, .i(1)] : 0,
      [.i(4), .dest] : 2,
      [.i(4), .feedback, .src, .i(0)] : 1,
      [.i(4), .feedback, .src, .i(1)] : 1,
      [.i(4), .adjust, .level] : 6,
      [.i(5), .src, .i(0)] : 0,
      [.i(5), .src, .i(1)] : 0,
      [.i(5), .dest] : 1,
      [.i(5), .feedback, .src, .i(0)] : 1,
      [.i(5), .feedback, .src, .i(1)] : 0,
      [.i(5), .adjust, .level] : 6,
    ],
  ]
}
